name: Hello World-build-Push
on: 
  push:
    braches:
      - main
      - develop
      - 'release/**'
  pull_request:
    branches:
      - main
jobs:
   build1:
     runs-on: ubuntu-latest
     steps:
       - name: Build1 Step
         run: echo "A demo1  build"